apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rajktestpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rajktestpipelinesjavascriptdocker 
    spec:
      containers:
        - name: rajktestpipelinesjavascriptdocker 
          image: rajkcontainerregistry.azurecr.io/rajktestpipelinesjavascriptdocker 
          ports:
          - containerPort: 8080